### ISSUE TITLE
Update proto files for 0.8.0 release

### ISSUE THREAD

**Issue by youngbupark** [dapr/rust-sdk#15]
Update proto files for 0.8.0 release

**Comment by gdhuper** [comment]
@youngbupark I would like to work on this. Could you assign me this? Thanks

**Comment by gdhuper** [comment]
@youngbupark Is this task still incomplete?

**Comment by youngbupark** [comment]
> @youngbupark Is this task still incomplete?

yesterday, there is proto file change in dapr upstream. Can you please update proto file again?

**Comment by gdhuper** [comment]
> > @youngbupark Is this task still incomplete?
> 
> yesterday, there is proto file change in dapr upstream. Can you please update proto file again?

Yes, of course.
