### ISSUE TITLE
Could the team release a newer version for Dapr rust sdk?

### ISSUE THREAD

**Issue by TonyPythoneer** [dapr/rust-sdk#180]
## Question

I'd like to use the latest version of `dpar_macro's topic` to build a pubsub application, but it doesn't release into 0.14.0

I wonder if you have a plan to release a newer version of the SDK.

Thank you.

**Comment by mikeee** [comment]
I'll be prepping for a release soon to coincide with Dapr v1.14 🙂

**Comment by mikeee** [comment]
v0.15.0 has been released
