### ISSUE TITLE
Automate cargo package publish process

### ISSUE THREAD

**Issue by youngbupark** [dapr/rust-sdk#33]
Automate cargo package publish process

**Comment by gdhuper** [comment]
Hi @youngbupark, can I work on this issue?

**Comment by gdhuper** [comment]
Hi @youngbupark, I have a few clarification questions:
- Do we have a dapr account on crates.io? 
- If so, I am assuming we want to create a CI/CD Github actions pipeline to publish the package automatically? Do I need special permissions to create a github actions pipeline?

**Comment by youngbupark** [comment]
> Hi @youngbupark, I have a few clarification questions:
> 
> * Do we have a dapr account on crates.io?

Thanks for this work. I do not have a permission to dapr crates.io. I am asking the owner of the crates to get the permission.

> * If so, I am assuming we want to create a CI/CD Github actions pipeline to publish the package automatically? Do I need special permissions to create a github actions pipeline?

yes, we want to publish the package automatically. you can just create https://github.com/dapr/python-sdk/tree/master/.github/workflows to enable actions for this repo. After you fork this repo, you can add workflow yaml and then test it. If you want to add the secret, you can add it in the setting. for the upstream repo, if you give me the secret variable name, then I will add dapr crates.io secret in the upstream repo.

**Comment by youngbupark** [comment]
@gdhuper you can use `CRATES_IO_TOKEN` secret value to log in crates.io.

**Comment by gdhuper** [comment]
Sounds good. Thanks for your help @youngbupark
