### ISSUE TITLE
Clarify "WIP" Status

### ISSUE THREAD

**Issue by theduke** [dapr/rust-sdk#41]
Hey there.

I considered starting work on a Dapr SDK, but was positively surprised to see an official one already in the works.

Could you update the README with some information on the current state of this project? 
As in: why is it WIP, what is supported, what isn't yet, etc.

**Comment by morigs** [comment]
+1
I think there should be a compatibility matrix or at least a list of unsupported features. Probably code coverage is also a useful metric for maturity

**Comment by tianlinzx** [comment]
Hope rust-sdk will be officially supported ASAP.

**Comment by hansmbakker** [comment]
@msfussell @dmitsh @pkedy @rumblefrog (seeing you were the last committers on this project)
would it be possible for you to add something to the README regarding the status of this project? and would it be possible for you to see whether something could be done with the PRs?
I see people try to contribute but it is not clear whether the project is maintained..
