### ISSUE TITLE
failed to build dapr v0.5.0 in rust-1.53.0-nightly

### ISSUE THREAD

**Issue by zhangshuiyong** [dapr/rust-sdk#47]
error: failed to run custom build command for `dapr v0.5.0`

Caused by:
  process didn't exit successfully: 

  error: the 'rustfmt' component which provides the command 'rustfmt' is not available for the 'nightly-x86_64-unknown-linux-gnu' toolchain

**Comment by cscetbon** [comment]
I think it should be closed with the current version being `1.12.4` and knowing it's been 2 and a half years now ...
