### ISSUE TITLE
Using invoke for HTTP endpoints not possible yet?

### ISSUE THREAD

**Issue by hbina** [dapr/rust-sdk#70]
I am trying to call some HTTP methods between 2 microservices set up using DAPR and I can't seem to figure out the way? Is it not possible yet? Glancing through the protobuf source and the generated code seems to indicate that the support is there? But the [invoke method](https://github.com/dapr/rust-sdk/blob/master/src/client.rs#L30-L51) doesn't provide any customization point to call using HTTP and defaults GRPC.

Sorry if this is silly, I only have basic knowledge of protobuf.

**Comment by hbina** [comment]
Also, the protobuf doesn't seem to indicate I can pass in headers as well....? What?

**Comment by liangyuanpeng** [comment]
#85  This PR may help.

**Comment by mikeee** [comment]
Closing for the time being, let us know if you need any further help
