### ISSUE TITLE
Publisher/subscriber example does not work

### ISSUE THREAD

**Issue by seekeramento** [dapr/rust-sdk#75]
**Steps:**
1- I opened a DAPR app on a given grpc port. The console shows that the Dapr is up and running.
2- Start the subscriber example in the elevated mode, and set the port to the sane one that Dapr is running at. The server will start fine. I noticed that it won't run in debug mode as it will not run in the elevated mode
3- Start the subscriber example. It will run fine. However, subscribers are not triggered upon publish events. 

**Expected Results:**
Subscribers must be triggered upon publish events

Additional Notes
The client example works fine, which indicates that the Dapr at least is operating as expected.

**Operating System:**
Windows 11

**Comment by liangyuanpeng** [comment]
It's working for me after change it  to 127.0.0.1:50051.

https://github.com/dapr/rust-sdk/blob/4cf17de437fa2e4ee891ea9e879055236110f705/examples/pubsub/subscriber.rs#L73

**Comment by NickLarsenNZ** [comment]
I don't have access to a Windows machine right now, but is IPv6 enabled/disabled?
I wondered whether `[::]` (all hosts) is only available when the IPv6 stack is enabled.

Is it any better when using `[::1]` (local host - which should also include for IPv4 interfaces but that could depend on the OS). In an example, localhost would probably be fine, but might be a bit misleading when implementing across network (eg: the dapr side car running on another host than the dapr app).

**Comment by NickLarsenNZ** [comment]
Also @seekeramento, do you see any sign of the subscriber app register with daprd?

Would you be able to share the output?

Another bit of useful output would be to see which interfaces are listening on TCP/50051.
From memory, something like `netstat -an -p tcp | find "50051"`. From that should should see whether it is indeed listening on only IPv4 or IPv4 interfaces, or both (when set to `[::]:50051`.

IMO, the examples should probably get the host and port from the environment, as I believe if run via `dapr run`, the application should see `DAPR_GRPC_HOST` and `DAPR_GRPC_PORT` set.

Here's how I've been doing it (granted, there might be a cleaner way):

```rs
const DAPR_GRPC_HOST_VAR: &str = "DAPR_GRPC_HOST";
const DEFAULT_DAPR_GRPC_HOST: &str = "[::1]";

const DAPR_GRPC_PORT_VAR: &str = "DAPR_GRPC_PORT";
const DEFAULT_DAPR_GRPC_PORT: &str = "50001";

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    ...

    // Figure out host:port to listen on, or fall back to const defaults
    let host = env::var(DAPR_GRPC_HOST_VAR).unwrap_or_else(|_| DEFAULT_DAPR_GRPC_HOST.to_owned());
    let port = env::var(DAPR_GRPC_PORT_VAR)
        .unwrap_or_else(|_| DEFAULT_DAPR_GRPC_PORT.to_owned())
        .parse::<u32>()
        .map_err(|e| anyhow!("unable to parse environment variable {DAPR_GRPC_PORT_VAR}: {e}"))?;

    let addr: SocketAddr = format!("{host}:{port}").parse().unwrap();
    let addr = format!("https://{addr}");

    tracing::info!(
        address = addr.to_string(),
        "connecting to dapr grpc server..."
    );

    let mut client = dapr::Client::<dapr::client::TonicClient>::connect(addr).await?;

   ...
}
```

**Comment by vonjackets** [comment]
I was able to get this to work after downgrading my Tonic crate to being the same as the sdk's (~0.8 at time of writing), and making sure that I ran  `dapr run` with `--app-protocol grpc` since dapr defaults to http. Hope this helps future posters

**Comment by mikeee** [comment]
Closing as stale
