### ISSUE TITLE
Example of a service call

### ISSUE THREAD

**Issue by nkasozi** [dapr/rust-sdk#76]
Hi,
I have looked through out the code but there doesnt seem to be any example of an `invoke_service` call. Am stuck on the data parameter `Option<Any>`. How do we pass a struct here with the necessary data. Are there any tests or docs that show example usage?

**Comment by hauju** [comment]
Hello @nkasozi , I added an example to invoke a service #85. One using the callback methods and the any type and one using the proxying feature from Dapr. Hope it helps you.

**Comment by nkasozi** [comment]
Hi @hauju thanks alot for this. I can close this now
