### ISSUE TITLE
Unable to add multiple subscriptions

### ISSUE THREAD

**Issue by NickLarsenNZ** [dapr/rust-sdk#81]
There is currently no way to add additional subscriptions. `ListTopicSubscriptionResponse::topic(...)` is hard coded to a vector of one subscription: https://docs.rs/dapr/0.9.0/src/dapr/appcallback.rs.html#42

_Originally posted by @NickLarsenNZ in https://github.com/dapr/rust-sdk/issues/80#issuecomment-1264086724_

---

Other SDKs seem to be able to do it (I have seen it in action with .Net), for example dapr/python-sdk:

https://github.com/dapr/python-sdk/blob/1aab2cb1e06b32899183a285eab5c975408d05b2/ext/dapr-ext-grpc/dapr/ext/grpc/app.py#L137-L140

**Comment by NickLarsenNZ** [comment]
Actually, it looks like I can if I avoid using the `topic` method, and instead build the struct from scratch like so:

```rs
    async fn list_topic_subscriptions(
        &self,
        _request: Request<()>,
    ) -> Result<Response<ListTopicSubscriptionsResponse>, Status> {
        // This commented out section only allows a single subscription
        // let list_subscriptions =
        //     ListTopicSubscriptionsResponse::topic(self.pubsub_name.clone(), self.topic.clone());
        let empty_metadata = None;

        let list_subscriptions = ListTopicSubscriptionsResponse {
            subscriptions: vec![
                TopicSubscription::new("pubsub".to_owned(), "a".to_owned(), empty_metadata.clone()),
                TopicSubscription::new("pubsub".to_owned(), "b".to_owned(), empty_metadata.clone()),
            ],
        };

        Ok(Response::new(list_subscriptions))
    }
```

**Comment by NickLarsenNZ** [comment]
It does appear to silently fail if you create two instances of the Dapr AppCallbackServers, like this which I had originally tried:

```
    Server::builder()
        .trace_fn(|_| tracing::info_span!("tonic server"))
        .add_service(AppCallbackServer::new(job_runner::JobRunner::new(
            pubsub.as_str(),
            topic.as_str(),
        )))
        .add_service(AppCallbackServer::new(job_runner::JobRunner::new(
            pubsub.as_str(),
            "another.topic",
        )))
        .serve(addr)
        .await?;
```

**Comment by mikeee** [comment]
https://github.com/dapr/rust-sdk/pull/87#issuecomment-1684854260
I think this can be addressed for now with the above merged. Let me know any thoughts otherwise :)
